### ISSUE TITLE
Community: Contribution Opportunities and Standards

### ISSUE THREAD

**Issue by em-ly** [RichardLitt/github-task-status#2]
Objective: Establish a community landing page that shows contributors the opportunities ("help wanted") with Protocol Lab's open source projects, and also present the standardization for contributions to IPFS.

**"help wanted"**
Right now the only way to see all available tasks is this [daunting list here](https://github.com/search?utf8=%E2%9C%93&q=label%3A%22difficulty%3Aeasy%22+user%3AIPFS+is%3Aopen&type=Issues&ref=searchresults), which doesn't emphasize what the most valuable contributions to the project could be. It would be great to have these broken out by project.

**Contribution Guidelines**
We have so many of these pages that it's become daunting and not useful. We want this information to be communicated clearly and I feel like we could use some reform in the way information is presented here. Would love to hear your thoughts! 

Links in question:
[IPFS/Community Contributing Guidelines](https://github.com/ipfs/community/blob/master/contributing.md)
[IPFS/Community Contribution Guidelines cont.](https://github.com/ipfs/community/blob/master/contribution-guidelines.md)
[IPFS Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) (should be it's own page, but wanted to be sure it gets included)
[Go Contributing Guidelines](https://github.com/ipfs/community/blob/master/go-contribution-guidelines.md)

**Comment by RichardLitt** [comment]
Ah! Sorry! this should be in ipfs/community.

**Comment by em-ly** [comment]
Roger!
